name: Hello World
author: Tom Brown
description: A simple action
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Tom
outputs:
  time:
    description: 'The greeting time'
runs:
  using: 'node12'
  main: 'dist/index.js'
