name: 'Open GitHub Issue'
author: 'Tom Brown'
description: 'Opens a GitHub Issue'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  title:
    description: 'Issue Title'
    required: true
  body:
    description: 'Issue Body'
    required: false
  assignees:
    description: 'Issue Assignees'
    required: false
outputs:
  issue:
    description: 'The issue object as a json string'
runs:
  using: 'node12'
  main: 'dist/index.js'